### PR TITLE
Update service name for SSH

### PR DESCRIPTION
**Pull request by Nintendofan885**
See https://wikitech.wikimedia.org/wiki/News/Toolforge.org#New_service_names_for_accessing_Toolforge_SSH_bastions for more information

### CODE REVIEW

**Comment by Tpt** [comment]
Thank you!

Why are you converting RDF namespaces URIs to https?
RDF considers that http and https URLs are differents. It will break all the existing queries and some parts of Ontop that relies on some basic vocabularies like http://www.w3.org/1999/02/22-rdf-syntax-ns#type or http://www.w3.org/2001/XMLSchema#string

**Comment by Nintendofan885** [comment]
@Tpt I've just switched them back to http

**Comment by Tpt** [comment]
Great! Thank you! @ghuron This PR changes the namespace for the mw: properties and, so, breaks the SPARQL queries using it. Do you think it's a big deal?

**Comment by ghuron** [comment]
I don't think it's a big deal, we just need to reflect it in https://www.mediawiki.org/wiki/MW2SPARQL

**Comment by Nintendofan885** [comment]
I've just updated the wiki page

**Pull request merged**
